apiVersion: v1
kind: Secret
metadata:
  name: mariadb
type: kubernetes.io/basic-auth
stringData:
  user: cscart
  database: cscart
  username: admin
  password: t0p-Secret
  host: mariadb-svc.default.svc.cluster.local