apiVersion: v1
kind: Secret
metadata:
  name: mariadb
type: kubernetes.io/basic-auth
stringData:
  user: cscart
  database: cscart
  username: admin
  password: t0p-Secret
  host: your-serverless-host
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
type: kubernetes.io/basic-auth
stringData:
  password: t0p-Secret
  host: your-serverless-host